[build]
  command = "npm run build"
  publish = "out" # if you use next export; remove/change if using plugin
  publish = ".netlify/output" # recommended when using @netlify/plugin-nextjs

[[plugins]]
  package = "@netlify/plugin-nextjs"